# Generated by Django 2.0.7 on 2018-07-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
