# Generated by Django 2.0.7 on 2018-07-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acounts',
            name='cookie',
            field=models.TextField(default=None),
        ),
    ]
