# Generated by Django 2.0.7 on 2018-07-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_website_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acounts',
            name='cookie',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='acounts',
            name='status',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
    ]
