# Generated by Django 2.0.7 on 2018-07-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_acounts_cookie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acounts',
            name='status',
            field=models.IntegerField(default=False),
        ),
    ]
