# Generated by Django 2.0.7 on 2018-07-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180716_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acounts',
            name='website',
            field=models.CharField(max_length=255),
        ),
    ]
