# Generated by Django 2.0.7 on 2018-07-16 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180716_1101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Website',
        ),
    ]
